### PR TITLE
Adding link to User guide

### PR DESCRIPTION
**Pull request by akaro2424**

### CODE REVIEW

**Comment by cameronwhite** [comment]
Thanks!

**Comment by akaro2424** [comment]
Hi Cameron,
Just noticed that it looks like the Pinta web site server appears to not
have updated its cache from GitHub as the link under documentation to the
User Guide does not appear to be updated yet on the site. Curious if this
is an automatic process or does it have to be updated manually?

Thanks for your help,
Ann

**Comment by cameronwhite** [comment]
I think it should have been updated automatically - I've notified Jonathan who did most of the work on the site

**Comment by akaro2424** [comment]
Thanks for notifying Johnathan.  I noticed , looking at the GitHub code it looks like the last merged update to the website code 3 years ago re installation is in the master code but is not on the live website. I suspect the website has not updated from the Github code automatically to the live site for some time. Hopefully Johnathan replies to your email request as I know his email address bounced on my original email to the two of you.

**Comment by cameronwhite** [comment]
Yeah I did hear back from Jonathan - it sounds like the website updating was handled by a VM that no longer exists, so the best option is likely to switch over to using Github Pages and point the pinta-project.com domain there

**Comment by akaro2424** [comment]
Hi Cameron,
Wondering do you plan on switching the Pinta website over to Github? Do you
need some help switching it over?
-Ann

**Comment by cameronwhite** [comment]
Yeah, contributions would be fantastic! It's been on my todo list but I haven't had much time to look into it

**Comment by cameronwhite** [comment]
I've resurrected https://github.com/PintaProject/pintaproject.github.io and ported over the current website's contents. Just looking now at pointing the domain name over to https://pintaproject.github.io/

**Comment by akaro2424** [comment]
Hi Cameron,
I noticed you resurrected the old git site which is great!
Some things came up the last few weeks that took me away from helping you
more on this - looks though like you are nearly there with regards to
moving the website over to Github pages.
I read through the steps to redirect the domain name:
https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#about-custom-domain-configuration
Hoping you are good with doing this (not sure I can help much on this
without the proper access).
Please let me know though if there is anything I can help with!
Ann

**Comment by cameronwhite** [comment]
Thanks! I'm just waiting to hear back from Jonathan on this - I don't have access to the DNS provider

**Comment by cameronwhite** [comment]
The DNS issues should be fixed now!

**Pull request merged**
